baseURL = "https://koi.science/"
languageCode = "en-us"
title = "Molecular Biology for your classroom"
theme = "initio"

publishDir = "docs"

[params]
    name = "Koi Science"
    description = "Molecular biology, made simple and affordable for your classroom"
    email = "info@koi.science"
    phone = "+86 186 8246 7503"
    address = "Our address in English"
    address_cn = "深圳 南山区 南头街道 麻雀岭工业区m10栋4号楼一楼 零空间"
    year = 2017
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showTools = true
    showKits = true
    showDownload = false
    showPartners = true

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = true
    footerEnableFormWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[[menu.main]]
    name = "Shop"
    url = "http://amazon.com"
    weight = 5

[[menu.main]]
    name = "Downloads"
    url = "/downloads/"
    weight = 5


[[params.social]]
    title = "twitter"
    url = "https://twitter.com/koi_science"
	icon = "fa-twitter-square"
	footer = true
	sharethis = true
	network = "twitter"
[[params.social]]
	title = "github"
	url = "https://github.com/koi-science"
	icon = "fa-github"
	footer = true
	sharethis = false
	network = ""

